#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header web-01 and web-02
#The name of the custom HTTP header is X-Served-By
#The value of the custom HTTP header is the hostname of the server Nginx is running on
#configures a brand new Ubuntu machine to the requirements asked in this task

apt-get update
apt-get install -y nginx
sudo mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart

