#!/usr/bin/env bash
#script that configures a server to run on Nginx
#and listening on port 80 of all the server’s active IPv4 IPs

cd /etc/nginx/sites-enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default default;
service nginx restart
