#!/usr/bin/env bash
#displays To infinity and beyond indefinitely
#between each iteration of the loop, sleep 2 is added 

num=0
while [ $num -lt 10 ]
do
  echo "To infinity and beyond"
  sleep 2
done
