#!/usr/bin/env bash
#displays To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#displays I am invincible!!! when receiving a SIGTERM signal

num=0
while [ $num -lt 10 ]
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
