#!/usr/bin/env bash
#loops through a statement with if condition

number=0
while [ $number -lt 10 ]
do
  if [ "$number" -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best school"
  (( number++ ))
  
done
